### ISSUE TITLE
Newest Bootstrap-Version?

### ISSUE THREAD

**Issue by Der-K-2000** [dannymachal/devdmbootstrap4#3]
First of all thank you very much to make this theme possible. That's a big help! 

**Is there any chance to update the libraries like bootstrap manually without waiting for your next release?** 

Currently the last version of bootstrap is [4.3.1](https://getbootstrap.com/docs/4.3), but the version in _devdmbootstrap4_ is [v4.1.1](https://github.com/dannymachal/devdmbootstrap4/blob/master/assets/css/devdmbootstrap/devdmbootstrap4.css).

The relevant file is placed in devdmbootstrap4/assets/css/**devdmbootstrap4.css**, but as far as I can see, it's a mixture of Bootstrap AND some other classes (starting with **.dmbs**). So it wouldn't make any sense to overwrite the file with the newest bootstrap-version, right?

Could you please separate the theme-css of the bootstrap-css **OR** do you have any idea to include the newest bootstrap? Thank you!

**Comment by dannymachal** [comment]
Hey Sebastian,

It is pretty hard to separate them out as many of the WordPress core features are actually extending some of the styles from the Bootstrap core SCSS mixins and classes. I've updated the master branch for version 1.81 of the theme that includes the bootstrap update and fontawesome update. I'll push out a release shortly.

**Comment by Der-K-2000** [comment]
Hi! Thanks for the update... and for the info I haven't realized so far. That sounds annoying! :-/
